experiment:
  name: "StudentTeacherQuantization"
  model_save_path: "./model" # path to save the trained model
  experiment_number: 0 # do not forget to change the experiment number

data:
  name: "DriveAndAct"
  util_location: "framework_activity_recognition.datautils.prepare_drivenact"
  split_nr: 0 # 1 2
  folder_splits: # path to folder containing split ex: "./driveandact/iccv_activities_3s/activities_3s/"
  data_path: # path to folder containing downsampled Drive&Act video data
  views: ["inner_mirror"]
  new_suffix: ".avi"
  sampler:
    use: True
    location: "framework_activity_recognition.sampler.ImbalancedDatasetSampler"
    parameter: {}
  n_frame: 16
  frame_size: 224

teacher:
  use: True
  location: "architecture.i3d.I3DLogit"
  modality: "rgb"
  dropout_prob: 0.5
  name: "inception"
  checkpoint: # path to I3D model trained with Drive&Act checkpoint ex: ./best_model.pth, adjust according splits

student:
  location: "architecture.mobilenetquant.MobileNetLogit"
  width_mult: 0.5
  dropout_prob: 0.2
  pool:
    kernel: 1
    width: 7
    height: 7

pretraining:
  use: True
  #student
  path: # path to MobileNet model pretrained with Kinetics-600
  student_model_num_classes: 600
  fine_tune_only_last_layer: False
  #teacher (used although pretraining["use"] = true)
  teacher_model_num_classes: 400
  last_layer_variable: "conv3d_0c_1x1"
  last_layer_class: "architecture.i3d.Unit3Dpy"
  last_layer_parameter: {"in_channels": 1024, "kernel_size": !!python/tuple [1, 1 ,1], "activation": null, "use_bias": True, "use_bn": False}

train:
  modality: "train_st_quant"
  epoch: 200
  criterion: 
    name : "CrossEntropyLoss"
  optimizer:
    name: "SGD"
    parameter: {"lr": 0.1, "momentum": 0.9, "weight_decay": 0.00001}
  batch_size: 32
  num_workers: 4
  scheduler:
    use: True
    name: "MultiStepLR"
    parameter: {"milestones": [50,100,200,300,400,500,600,700], "gamma": 0.2}
  test_rate: 5
  quantization:
    use: True
    fuse_module: [['features.0.0', 'features.0.1', 'features.0.2'], 
    ['features.1.conv1', 'features.1.bn1'], ['features.1.conv2', 'features.1.bn2', 'features.1.relu'],
    ['features.2.conv1', 'features.2.bn1'], ['features.2.conv2', 'features.2.bn2', 'features.2.relu'],
    ['features.3.conv1', 'features.3.bn1'], ['features.3.conv2', 'features.3.bn2', 'features.3.relu'],
    ['features.4.conv1', 'features.4.bn1'], ['features.4.conv2', 'features.4.bn2', 'features.4.relu'],
    ['features.5.conv1', 'features.5.bn1'], ['features.5.conv2', 'features.5.bn2', 'features.5.relu'],
    ['features.6.conv1', 'features.6.bn1'], ['features.6.conv2', 'features.6.bn2', 'features.6.relu'],
    ['features.7.conv1', 'features.7.bn1'], ['features.7.conv2', 'features.7.bn2', 'features.7.relu'],
    ['features.8.conv1', 'features.8.bn1'], ['features.8.conv2', 'features.8.bn2', 'features.8.relu'],
    ['features.9.conv1', 'features.9.bn1'], ['features.9.conv2', 'features.9.bn2', 'features.9.relu'],
    ['features.10.conv1', 'features.10.bn1'], ['features.10.conv2', 'features.10.bn2', 'features.10.relu'],
    ['features.11.conv1', 'features.11.bn1'], ['features.11.conv2', 'features.11.bn2', 'features.11.relu'],
    ['features.12.conv1', 'features.12.bn1'], ['features.12.conv2', 'features.12.bn2', 'features.12.relu'],
    ['features.13.conv1', 'features.13.bn1'], ['features.13.conv2', 'features.13.bn2', 'features.13.relu']]
    backend: 'fbgemm'
    freeze_observer: 150
    freeze_bn: 150
  temperature: 3
  teacher_weight: 0.9

config:
  path: "./config/train/studentteacher_quant.yaml"
